version: "3.9"
services:

  backend:
    build:
      context: ../backend
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - mongo
    env_file:
      - backend.env
    volumes:
      - ../backend/src:/app/src

  mongo:
    image: mongo:6.0.8
    restart: on-failure
    ports:
      - 27018:27017
    env_file:
      - mongo.env
    volumes:
      - ./data:/data/db