version: "3.9"
services:

  backend:
    image: alejoide/bcra-scraper-api:latest
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - backend.env

  mongo:
    image: mongo:6.0.8
    restart: unless-stopped
    env_file:
      - mongo.env
    volumes:
      - ./data:/data/db
