version: "3.9"
services:

  backend:
    image: alejoide/bcra-scraper-api:latest
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .backend.env
    networks:
      - default
      - nginx-proxy

  mongo:
    image: mongo:7.0.4
    restart: unless-stopped
    env_file:
      - .mongo.env
    volumes:
      - ./data:/data/db


# Only for production environments when using jwilder/nginx-proxy.
networks:
  nginx-proxy:
    external: true
