version: "3.9"
services:
  bcra-scraper-api:
    image: alejoide/bcra-scraper-api:latest
    container_name: bcra-scraper-api
    build:
      context: ../src/
      dockerfile: ../src/Dockerfile
    volumes:
      - ../src:/app/src
    restart: no
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - mongo

networks:
  mongo:
    external: true
