version: "3.9"
services:
  bcra-scraper-api:
    image: alejoide/bcra-scraper-api:latest
    container_name: bcra-scraper-api
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - mongo

networks:
  mongo:
    external: true
