version: "3.9"
services:
  BCRA-Scraper-API:
    image: alejoide/bcra-scraper-api:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - mongo

networks:
  mongo:
    external: true
