name: deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to production
    runs-on: self-hosted
    environment: prod
    steps:
    -
      name: Checkout
      uses: actions/checkout@master
    -
      name: Setting up Stack
      run: |
        mkdir -p $PROJECT_PATH
        cp -f ./deploy/prod.compose.yml $PROJECT_PATH/docker-compose.yml
        echo "$BACKEND_ENV_CONTENT" > $PROJECT_PATH/.backend.env
        echo "$MONGO_ENV_CONTENT" > $PROJECT_PATH/.mongo.env
      env:
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        BACKEND_ENV_CONTENT: ${{ secrets.BACKEND_ENV_CONTENT }}
        MONGO_ENV_CONTENT: ${{ secrets.MONGO_ENV_CONTENT }}
    -
      name: Pull changes and restart
      run: |
        cd ${{ secrets.PROJECT_PATH }}
        docker compose down --remove-orphans
        docker compose pull
        docker compose up -d
